### ISSUE TITLE
Details on Fastload protocol

### ISSUE THREAD

**Issue by picontrolit** [RhinoDevel/cbmtapepi#1]
Hello RhinoDevel,
it would be great if you could share some details on the fastload protocol. 
I am currently using a DIY (Arduino based) Tapuino "datasette". 
A fastmode for it would be fantastic.
BR,
Alex

**Comment by RhinoDevel** [comment]
Hi Alex,

the details are available in the code:

- [cbm](https://github.com/RhinoDevel/cbmtapepi/tree/master/cbm) holds the Commodore client code.
- [app/petload](https://github.com/RhinoDevel/cbmtapepi/tree/master/app/petload) the Pi server code.

Also take a look at the file [protocol.txt](https://github.com/RhinoDevel/cbmtapepi/blob/master/docs/protocol.txt), but beware, it is in a _work-in-progress_ state.

The protocol currently "handshakes" every bit, this is why the fast mode's rate is around 2.5kByte/s, only (still much faster than tape).

The implementation is specific to the way the datassette port connections are used (MOTOR, READ, WRITE, SENSE), see [connecting circuit](https://github.com/RhinoDevel/cbmtapepi/blob/master/docs/CBM%20tape%20to%20Raspberry%20Pi%20(Marcel%20Timm%2C%20RhinoDevel).png).

I do not know if/how this is applicable to Tapuino as I do not know how Tapuino works / what it can do.

**Comment by picontrolit** [comment]
Many thanks. For the Tapuino I followed http://sweetlilmre.blogspot.com/2014/07/tapuino-20-c64-tape-emulator.html
It works like a charm (using tap files) but the speed is dead slow.

**Comment by RhinoDevel** [comment]
> Many thanks. For the Tapuino I followed http://sweetlilmre.blogspot.com/2014/07/tapuino-20-c64-tape-emulator.html
> It works like a charm (using tap files) but the speed is dead slow.

CBM Tape Pi's fast mode would work with "default" (Commodore format) TAP files,
but not with TAP files using a custom format (tape fast loaders, copy protection stuff, etc.).
I am pretty sure that would be true for a fast mode added to Tapuino, too.

What I would like to do is porting CBM Tape Pi to Arduino, but there are no concrete plans.
