### ISSUE TITLE
10 kOhm resistor R1 (for the LED) 

### ISSUE THREAD

**Issue by picontrolit** [RhinoDevel/cbmtapepi#3]
The 10kOhm is too much for R1 (you can hardly see it).
A typical value for driving a LED is rather 150..500 Ohm.

**Comment by RhinoDevel** [comment]
Added a hint (my LED is bright enough, but you are right): https://github.com/RhinoDevel/cbmtapepi/commit/23c164f6923c37bef1d5db48838063c12cadaf4e
