### ISSUE TITLE
How to switch off fast mode?

### ISSUE THREAD

**Issue by picontrolit** [RhinoDevel/cbmtapepi#4]
Hello,
I am missing an example in the README.md on how to turn off fast mode. Looking at the code, it should be mode="save".
So it is "!mode save" or is it SAVE"MODE SAVE"?
Alex

**Comment by RhinoDevel** [comment]
The information is already included in the current [README](https://github.com/RhinoDevel/cbmtapepi/blob/master/README.md).

**Comment by picontrolit** [comment]
I don't think so. The list of supported modes does not mention a mode to switch back to compatibility mode.

**Comment by RhinoDevel** [comment]
You are right.

Here are the changes: https://github.com/RhinoDevel/cbmtapepi/commit/5f4da5128658016e82d8df5ac29be4d76dbe3580

Thanks.

By the way: Don't hesitate to create a pull request next time.
