### ISSUE TITLE
HW possible review?

### ISSUE THREAD

**Issue by dr-prodigy** [RhinoDevel/cbmtapepi#6]
Hi, first of all, congrats for your great project! 👍 
I was wondering: would it be feasible/correct to replace the 4 transistors with a Bi-Directional Logic Level Converter such as this one
https://www.adafruit.com/product/757
therefore simplifying the circuit further, and (most probably) protect both sides from wrong voltages (I'm thinking both about inadventent I/O toggles, and C64 & Pi power on/offs)?

Thank you very much, and KUTGW! 👍

**Comment by RhinoDevel** [comment]
@dr-prodigy Thanks for the nice words!

About your question:

Using logic level converters may be possible for at least some of the connections, but I cannot answer that question without further investigation.

CBM Tape Pi is not just for the C64 and therefore the circuit must also work with other Commodore machines (currently VIC 20 and PET series) whose internal datassette circuitry is slightly different.
E.g. some computers have internal pull-up resistors attached to the SENSE and READ line (or inside the connected ICs like 6520, 6522 or 6526) and others not.
This is (for example) the reason, why BCM10 and READ are connected with the two-transistor combination.

The current interfacing circuit works for the supported machines and I thought a lot about it (and tested a lot) to let it be as safe as possible while using the simplest discrete components, only.

By the way: Powering the Commodore and Pi on/off in another order than described in the README should cause no harm, it is just not "officially recommended".

**Comment by dr-prodigy** [comment]
Hi @RhinoDevel
sorry for the belated answer, and thank you very much again: very interesting answer!

Your explanation provides a lot more light on what, in my (limited) electronics understanding, I could see from the analysis of your schemes: the 2-transistor was in fact one on my biggest doubts.

My worry was mainly regarding the powering sequence and the possibility of harming my (beloved) c64; if there is no real risk on that side (although I will avoid stress on the hw anyway, I'm glad to hear that I can sometimes "forget" the exact order), I completely like your neat design: extremely convenient, easy and cheap.

I will soon prepare my CBMTapePi: thanks for your great work, I really appreciate it!
Cheers
dr-p
