### ISSUE TITLE
Need troubleshooting tips

### ISSUE THREAD

**Issue by picontrolit** [RhinoDevel/cbmtapepi#7]
Hello, 
my CBM tape PI (RPi 1) was working perfectly fine. But today it gives me some headache.
I enabled the debug kernel and it shows:

...
kernel_main : Mode  to use has value 0.
cmd_enter : Entered function.
tape_receive: Setting sense line to LOW at CBM..
tape_receive: Receiving data..
tape_receive_buf: Motor is OFF, waiting..
tape_receive_buf: Motor is ON, starting..

The last line appears after turning on the Pet (CBM8032).
What would be next after "tape_receive_buf: Motor is ON, starting.." normally? An LOAD command from the Pet shows "Searching" for ever and no output on the Debug console.

**Comment by RhinoDevel** [comment]
Mode 0 is the compatibility mode where you have to use the SAVE command first (see README).
